format_version: 10
pipelines:
  expense-create:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a15a35c:
        git: https://github.com/spatil-Devops/expense-terraform.git
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:j91hxwVAbj4VqDtcB+jm0w==:YCRKBloh/y76NMig8WlCXw=="
      vault_token: "AES:CGxtA/YfGkEZc0OMDPfuFQ==:Sbiyc+ZnvKcPb2jXS57baUl/4Egw+ushzjoIn/OwhDU="
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform:
              timeout: 0
              tasks:
              - exec: { command: bash, arguments: ["run.sh"]}

      - PROD:
          fetch_materials: true
          environment_variables:
            env: prod
          approval:
            type: manual
          jobs:
            terraform:
              timeout: 0
              tasks:
                - exec: { command: bash, arguments: ["run.sh"]}