format_version: 10
pipelines:
  expense-destroy:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a15a35c:
        git: https://github.com/spatil-Devops/expense-terraform.git
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform:
              timeout: 0
              tasks:
              - exec: { command: terraform, arguments: ["init", "-backend-config", "env-dev/state.tfvars"]}
              - exec: { command: terraform, arguments: ["destroy", "-var-file", "env-dev/main.tfvars", "-auto-apporve"]}

      - PROD:
          fetch_materials: true
          environment_variables:
            env: prod
          approval:
            type: manual
          jobs:
            terraform:
              timeout: 0
              tasks:
                - exec: { command: terraform, arguments: ["init", "-backend-config", "env-prod/state.tfvars"]}
                - exec: { command: terraform, arguments: ["destroy", "-var-file", "env-prod/main.tfvars", "-auto-apporve"]}
