format_version: 10
pipelines:
  backend:
    group: App-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a15a35c:
        git: https://github.com/spatil-Devops/expense-shell.git
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:j91hxwVAbj4VqDtcB+jm0w==:YCRKBloh/y76NMig8WlCXw=="
    environment_variables:
      component: backend
    template: ansible-app-deployment