format_version: 10
pipelines:
  mysql:
    group: App-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a15a35c:
        git: https://github.com/spatil-Devops/expense-shell.git
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:WuN8P9DnNAcdDOMlwrj5jQ==:/4bV5YOpAv/ywtHjCNn3xQ=="
    environment_variables:
      component: mysql
    stages:
    - DEV:
        fetch_materials: true
        environment_variables:
          env: dev
        jobs:
          ansible:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - run.sh
                command: bash
    - QA:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - -l
                  command: ls
                  run_if: passed
    - Stage:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - -l
                  command: ls
                  run_if: passed
    - Prod:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - -l
                  command: ls
                  run_if: passed