format_version: 10
pipelines:
  prometheus:
    group: Tools
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a15a35c:
        git: https://github.com/spatil-Devops/tools-automation.git
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:j91hxwVAbj4VqDtcB+jm0w==:YCRKBloh/y76NMig8WlCXw=="
      vault_token: "AES:uCYHEw8lVKq1uuJolkJIJw==:Wk1wDF0KJh1im2iW8Tem0/Jn84ygZol7OlE0/EAf+Gs="
    environment_variables:
      tool_name: prometheus
    stages:
      - create:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            terraform:
              timeout: 0
              tasks:
              - exec:
                  command: bash
                  arguments: ["setup-tools.sh"]
